<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <LangVersion>9.0</LangVersion>
    <OutputType>Exe</OutputType>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <AssemblyName>Perf</AssemblyName>
    <StartupObject>Perf</StartupObject>
    <Optimize>true</Optimize>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\UnityShim.cs" />
    <Compile Include="..\TestData.cs" />
    <Compile Include="Perf.cs" />
    <Compile Include="..\..\..\Assets\Scripts\**\*.cs" />
  </ItemGroup>
</Project>
